<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daily Attendance History Report</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .header h1 { margin: 0; font-size: 20px; text-transform: uppercase; }
        .header p { margin: 5px 0 0; color: #666; font-size: 11px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }
        th { background-color: #f4f4f4; text-transform: uppercase; font-size: 9px; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .late { color: red; font-weight: bold; }
        .on-time { color: green; }
        .footer { position: fixed; bottom: -20px; left: 0px; right: 0px; height: 50px; text-align: center; font-size: 9px; color: #999; }
    </style>
</head>
<body>

    <div class="header">
        <h1>Attendance History Report</h1>
        <p>Smart IoT Attendance App - Printed on: {{ \Carbon\Carbon::now()->format('d M Y, H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Date</th>
                <th>Employee Name</th>
                <th>Department</th>
                <th>Check-in</th>
                <th>Check-out</th>
                <th>Work Duration</th>
                <th>Status</th>
                <th>Lateness (Limit 07:00)</th>
            </tr>
        </thead>
        <tbody>
            @forelse($logs as $index => $log)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $log->Tanggal ? $log->Tanggal->format('d M Y') : '-' }}</td>
                <td>{{ $log->employee->Nama ?? 'Unknown' }}</td>
                <td>{{ $log->employee->department->Nama_departemen ?? '-' }}</td>
                <td>{{ $log->Jam_masuk ?? '-' }}</td>
                <td>{{ $log->Jam_keluar ?? '-' }}</td>
                <td>{{ $log->Jam_keluar ? $log->Durasi . ' Mins' : '-' }}</td>
                <td>{{ ucfirst($log->Status) }}</td>
                <td>
                    @if($log->Status === 'telat' && $log->late_minutes > 0)
                        <span class="late">Late {{ $log->late_minutes }} Mins</span>
                    @elseif($log->Status === 'hadir')
                        <span class="on-time">On Time</span>
                    @else
                        <span>-</span>
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="9" style="text-align: center;">No data found for the selected filter.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Automatically Generated by Abscent IoT
    </div>
</body>
</html>
